### ISSUE TITLE
App Crashed at the end of transcription process on OSX 14.2.1

### ISSUE THREAD

**Issue by l4zz4r0** [Vaida12345/PianoTranscription#3]
**When did it crash?**
It crashes during transcription , at the end before preview window pop up.

**Have you tried the *Memory Saver Mode*?**
No

**Can I have the audio please?**
No midi produced due to crash during transcription

**Tell me about your device**
MacBook Pro 2018 Sonoma 14.2.1

**What is the application version?**
Latest version from AppStore 1.1 (30)

**Anything else you would like to add?**
No

**Comment by Vaida12345** [comment]
Thank you for your report, but I would need some more info. Can you provide me with the original audio please?

**Comment by l4zz4r0** [comment]
Hi,

file size exceeds (4mb mp3)

Can you provide an alternative email or maybe I could send it through WeTransfer …

let me know

Thank you so much

Regards

Paolo
Il 8 gen 2024, 08:39 +0100, Vaida ***@***.***>, ha scritto:

**Comment by Vaida12345** [comment]
Sure, Please send it to my email, developer@vaidaf.net

**Comment by Vaida12345** [comment]
Can you also send me the crash report please? You can find it using the `Console` App. Navigate to the `Crash Reports` on the left hand side, right click on Piano Transcriptionist, choose `Reveal in Finder`, and send me the `ipa` file. That would be great help. Thank you.

**Comment by l4zz4r0** [comment]
Hi,

crash report log on attach

thank you so much
Il 8 gen 2024, 08:51 +0100, Vaida ***@***.***>, ha scritto:

**Comment by Vaida12345** [comment]
Hey.
I apologies but I cannot fix this issue for now, as I suspect this issue would only appear on Intel-based Macs. Without an Intel-based Mac, I cannot reproduce the issue.
I will try to resolve this issue later, when I can get my hands on my old Mac.
From the shell outputs, it was obvious that the inference went wrong, as `null` value was produced. As the new version, ver 1.1 was all about optimizing the inference, please using the previous one instead. You can find the old version in [release](https://github.com/Vaida12345/PianoTranscription/releases/tag/v1.0.5-intel).
There could be something wrong with the driver to CoreML Packages, I have encountered this issue before, where arm based Macs run fine while intel based Macs would crash, throwing a bunch of garbages. 
Currently, please continue to use the old version. Or, use your iPhone or iPad. Due to optimizations, the app on your mobile device would actual run faster than the old version on Mac.

**Comment by Vaida12345** [comment]
This issue is now resolved, there is something wrong with the `vDSP` c interfaces in the `Accelerate` framework. 
To anyone in the future, (probability myself), these few lines caused the issue on intel-based Macs.
```swift
let count = vDSP_Length(self.count)
var one: Float = 1.0
vDSP_vneg(buffer.baseAddress!, 1, buffer.baseAddress!, 1, count) // Negate the values
var _count = UInt32(count)
vvexpf(buffer.baseAddress!, buffer.baseAddress!, &_count)          // Apply exp to each value
vDSP_vsadd(buffer.baseAddress!, 1, &one, buffer.baseAddress!, 1, count) // Add 1 to each value
vDSP_svdiv(&one, buffer.baseAddress!, 1, buffer.baseAddress!, 1, count) // Divide 1 by each value
```
`nan` values were returned, when it is impossible to get undefined values in `sigmoid` functions.

When `!arch(arm64)`, a `while` loop will be used instead.
I will be releasing the new version soon. This issue is now closed.

**Comment by Vaida12345** [comment]
Well, it seems that GPT screwed me up. I should have used a pointer to a signed integer instead of an unsigned one. Still wondering why it works on arm-based Macs.
